MODULE  DATA
  IMPLICIT  NONE
  INTEGER,     PARAMETER :: LENGTH_OF_LINE = 60
  INTEGER,     PARAMETER :: N_OF_LINES_OF_BRAILLS = 3
  INTEGER,     PARAMETER :: N_OF_COLUMNS_OF_BRAILLS = 2
  INTEGER,     PARAMETER :: N_OF_TYPES = 10
  INTEGER,     PARAMETER :: TYPE_OF_BASE_CHECK = 0
  INTEGER,     PARAMETER :: TYPE_OF_NUMBERS = 1
  INTEGER,     PARAMETER :: TYPE_OF_E_LETTERS = 2
  INTEGER,     PARAMETER :: TYPE_OF_E_PUNCTUATIONS = 3
  INTEGER,     PARAMETER :: TYPE_OF_C_SHENGMU = 4
  INTEGER,     PARAMETER :: TYPE_OF_C_YUNMU = 5
  INTEGER,     PARAMETER :: TYPE_OF_C_SHENGDIAO = 6
  INTEGER,     PARAMETER :: TYPE_OF_C_PUNCTUATIONS = 7
  INTEGER,     PARAMETER :: TYPE_OF_ALL_INDIVIDULLY = 8
  INTEGER,     PARAMETER :: TYPE_OF_ALL_COMBINED = 9
  INTEGER,     PARAMETER :: TYPE_OF_C_SYSYS = 10
  INTEGER,     PARAMETER :: N_OF_EMPTY_LINES = 2
  INTEGER,     PARAMETER :: N_OF_EMPTY_CHARS = 2
  INTEGER,     PARAMETER :: LENGTH_OF_ANSWERS = N_OF_EMPTY_CHARS * 2 + 2
  INTEGER,     PARAMETER :: N_OF_LINES_OF_ANSWERS = 5
  INTEGER,     PARAMETER :: N_OF_LINES_OF_MEANINGS = 10
  INTEGER,     PARAMETER :: BRAILLS_SHAPE(2) = (/N_OF_LINES_OF_BRAILLS, N_OF_COLUMNS_OF_BRAILLS/)
  !CHARACTER*1, PARAMETER :: BRAILL_DOTS(0:1) = (/'_', CHAR(223)/)
  CHARACTER*1, PARAMETER :: BRAILL_DOTS(0:1) = (/'_', 'D'/)
  CHARACTER*3, PARAMETER :: STARTING_LINE = '***'
  INTEGER,     PARAMETER :: N_OF_EMPTY_LINES_U = (N_OF_EMPTY_LINES + 1) / 2
  INTEGER,     PARAMETER :: N_OF_EMPTY_LINES_D = (N_OF_EMPTY_LINES    ) / 2


  INTEGER,     PARAMETER :: N_OF_BRAILL_BASES = 2**(N_OF_LINES_OF_BRAILLS*N_OF_COLUMNS_OF_BRAILLS)
  INTEGER                :: BRAILL_BASES(N_OF_LINES_OF_BRAILLS, N_OF_COLUMNS_OF_BRAILLS, N_OF_BRAILL_BASES)
  INTEGER                :: N_OF_ALL_MEANINGS(N_OF_BRAILL_BASES)
  CHARACTER (LEN=LENGTH_OF_ANSWERS) :: ALL_MEANINGS(N_OF_LINES_OF_MEANINGS, N_OF_BRAILL_BASES)
  INTEGER                :: TYPE_RANGE_OF_BRAILLS(2, N_OF_TYPES)
  INTEGER                :: THE_TYPE, THE_PRACTICE_TYPE


  INTEGER,     PARAMETER :: N_OF_BRAILLS = 500
  INTEGER                :: TOTAL_BRAILLS
  INTEGER                :: BRAILLS(N_OF_LINES_OF_BRAILLS, N_OF_COLUMNS_OF_BRAILLS, N_OF_BRAILLS)
  CHARACTER (LEN=LENGTH_OF_ANSWERS) :: ANSWERS(N_OF_LINES_OF_ANSWERS, N_OF_BRAILLS)


  INTEGER,     PARAMETER :: N_OF_BRAILLS_PER_LINE = 30
  INTEGER,     PARAMETER :: N_OF_PRACTICE_BRAILLS_PER_LINE = 3
  CHARACTER*1            :: RRR
  INTEGER                :: BRAILL_FROM = 1
  INTEGER                :: BRAILL_TO = 56
  INTEGER                :: BRAILL_RANGE = 56
  INTEGER                :: BRAILL_QUESTIONS(N_OF_BRAILLS_PER_LINE)
  INTEGER                :: STARTING_POSITION_IN_LINE
  CHARACTER (LEN=LENGTH_OF_LINE) :: BRAILL_LINES(N_OF_LINES_OF_BRAILLS) = ' '
  CHARACTER (LEN=LENGTH_OF_LINE) :: ANSWER_LINES(MAX(N_OF_LINES_OF_ANSWERS,N_OF_LINES_OF_MEANINGS)) = ' '

  INTEGER                :: QUESTION_NUMBER = 0

  INTEGER, POINTER, DIMENSION(:) :: FINAL_RESULT_IN_THREAD=>NULL()
END MODULE  DATA


MODULE  INTERFACES

  INTERFACE
     INTEGER FUNCTION GET_A_BRAILL()
       IMPLICIT  NONE
     END FUNCTION GET_A_BRAILL

     INTEGER FUNCTION GET_BASE_DECIMAL(BBB)
       IMPLICIT  NONE
       INTEGER :: BBB(3,2)
     END FUNCTION GET_BASE_DECIMAL
  END INTERFACE

END MODULE  INTERFACES


MODULE ALL_MODULES
  USE DATA
  USE INTERFACES
END MODULE  ALL_MODULES




PROGRAM BRAILL_PRACTICES
  USE   ALL_MODULES
  IMPLICIT  NONE
  CALL  PRACTICE_TYPE_CHOOSE()
  CALL  DATA_INITIALIZE()
  IF (THE_PRACTICE_TYPE == TYPE_OF_BASE_CHECK) THEN
      CALL  DATA_BASE_CHECK()
  ELSE
      CALL  PRACTICE()
  END IF
  CALL  DATA_FINALIZE()
  STOP
END PROGRAM BRAILL_PRACTICES




SUBROUTINE PRACTICE_TYPE_CHOOSE()
  USE ALL_MODULES
  IMPLICIT  NONE
  WRITE(*,*) "PLEASE CHOOSE ONE OF THE FOLLOWING PRACTICE TYPES:"
  WRITE(*,*) TYPE_OF_BASE_CHECK,      ":  All base braills checkup only;"
  WRITE(*,*) TYPE_OF_NUMBERS,         ":  0, 1, 2, till 9 numbers only;"
  WRITE(*,*) TYPE_OF_E_LETTERS,       ":  English 26 Letters only;"
  WRITE(*,*) TYPE_OF_E_PUNCTUATIONS,  ":  English Punctuations only (to be enabled);"
  WRITE(*,*) TYPE_OF_C_SHENGMU,       ":  Chinese Shengmu only;"
  WRITE(*,*) TYPE_OF_C_YUNMU,         ":  Chinese Yunmu only;"
  WRITE(*,*) TYPE_OF_C_SHENGDIAO,     ":  Chinese Shengdiao;"
  WRITE(*,*) TYPE_OF_C_PUNCTUATIONS,  ":  Chinese Punctuations only (to be enabled);"
  WRITE(*,*) TYPE_OF_ALL_INDIVIDULLY, ":  All Individually;"
  WRITE(*,*) TYPE_OF_ALL_COMBINED,    ":  All Combined;"
  WRITE(*,*) TYPE_OF_C_SYSYS,         ": Chinese Sheng+yun+sheng+yun+shengdiao."
  READ(*,*)  THE_PRACTICE_TYPE
  RETURN
END SUBROUTINE PRACTICE_TYPE_CHOOSE




SUBROUTINE DATA_INITIALIZE()
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER              :: I,J,K, I1,I2,I3,I4,I5,I6
  INTEGER              :: SEED_SIZE
  INTEGER, ALLOCATABLE :: SEED_NEW_VALUES(:)


  WRITE(*,*) "Please also supply a random integer: "
  READ(*,*) I6
  CALL RANDOM_SEED( )
  CALL RANDOM_SEED(SIZE=SEED_SIZE )
  ALLOCATE(SEED_NEW_VALUES(SEED_SIZE))
  DO I=1, SEED_SIZE
     SEED_NEW_VALUES(I)=BRAILL_FROM+I+I6
  END DO
  CALL RANDOM_SEED(PUT=SEED_NEW_VALUES)
  DEALLOCATE(SEED_NEW_VALUES)

  K = 0
  DO I6 = 0, 1
  DO I5 = 0, 1
  DO I4 = 0, 1
  DO I3 = 0, 1
  DO I2 = 0, 1
  DO I1 = 0, 1
     K = K + 1
     BRAILL_BASES(:, :, K) = RESHAPE((/I1,I2,I3,I4,I5,I6/), BRAILLS_SHAPE)
     IF(K.NE.GET_BASE_DECIMAL(BRAILL_BASES(:, :, K))) THEN
        WRITE(*,*) 'PROBLEM IN BRAILL_BASES: ', K, BRAILL_BASES(:, :, K), &
                    GET_BASE_DECIMAL(BRAILL_BASES(:, :, K))
        STOP
     END IF
  END DO
  END DO
  END DO
  END DO
  END DO
  END DO


  BRAILLS = 100
  ANSWERS = ' '
  K=0




  ! TYPE_OF_NUMBERS
  THE_TYPE = TYPE_OF_NUMBERS

  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  1   '

  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  2   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   3  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   4  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   5  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   6  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   7  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   8  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   9  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   0  '


  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K




  ! TYPE_OF_E_LETTERS
  THE_TYPE = TYPE_OF_E_LETTERS

  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  a   '

  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  b   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   c  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   d  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   e  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   f  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   g  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   h  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   i  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   j  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  k   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  l   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   m  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   n  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   o  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   p  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   q  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   r  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   s  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   t  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  u   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  v   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   w  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   x  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   y  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   z  '


  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K




  ! TYPE_OF_E_PUNCTUATIONS
  THE_TYPE = TYPE_OF_E_PUNCTUATIONS
  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K
  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K




  ! TYPE_OF_C_SHENGMU
  THE_TYPE = TYPE_OF_C_SHENGMU

  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  b   '

  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   p  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   m  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   f  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   d  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   t  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   n  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  l   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   g  '
  ANSWERS(2,K) = '   j  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  k   '
  ANSWERS(2,K) = '  q   '

  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   h  '
  ANSWERS(2,K) = '   x  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  zh  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   ch '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  sh  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   r  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   z  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   c  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   s  '


  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K




  ! TYPE_OF_C_YUNMU
  THE_TYPE = TYPE_OF_C_YUNMU

  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   a  '

  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '    o '
  ANSWERS(2,K) = '    e '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   i  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  u   '
  ANSWERS(2,K) = '  u   '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  uu  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   er '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   ie '
  ANSWERS(2,K) = '   ye '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   uo '
  ANSWERS(2,K) = '   wo '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  uue '
  ANSWERS(2,K) = '  yue '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ia  '
  ANSWERS(2,K) = '  ya  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ua  '
  ANSWERS(2,K) = '  wa  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ai  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  uai '
  ANSWERS(2,K) = '  wai '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ei  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   ui '
  ANSWERS(2,K) = '  wei '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ao  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,1,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  iao '
  ANSWERS(2,K) = '  yao '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '   ou '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  iu  '
  ANSWERS(2,K) = '  you '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  an  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ian '
  ANSWERS(2,K) = '  yan '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  uan '
  ANSWERS(2,K) = '  wan '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,1,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' uuan '
  ANSWERS(2,K) = ' yuan '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  en  '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,1,0,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  in  '
  ANSWERS(2,K) = '  yin '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,0,1,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  un  '
  ANSWERS(2,K) = '  wen '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,0,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  uun '
  ANSWERS(2,K) = '  yun '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ang '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,1,1,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' iang '
  ANSWERS(2,K) = ' yang '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' uang '
  ANSWERS(2,K) = ' wang '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  eng '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,0,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ing '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,0,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = '  ong '
  ANSWERS(2,K) = ' weng '


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,1,1,1/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' iong '
  ANSWERS(2,K) = ' yong '


  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K




  ! TYPE_OF_C_SHENGDIAO
  THE_TYPE = TYPE_OF_C_SHENGDIAO

  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/1,0,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' yinp '

  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,0,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' yangp'


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,0,1,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' shang'


  K = K + 1
  BRAILLS(:, :, K) = RESHAPE((/0,1,1,0,0,0/), BRAILLS_SHAPE)
  ANSWERS(1,K) = ' qushg'


  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K




  ! TYPE_OF_C_PUNCTUATIONS
  THE_TYPE = TYPE_OF_C_PUNCTUATIONS
  TYPE_RANGE_OF_BRAILLS(1, THE_TYPE) = K
  TYPE_RANGE_OF_BRAILLS(2, THE_TYPE) = K

  TOTAL_BRAILLS = K

  IF(N_OF_BRAILLS .LT. TOTAL_BRAILLS) THEN
     WRITE(*,*) 'TOO MANY BRAILLS IN DATA_INITIALIZE: ', N_OF_BRAILLS, TOTAL_BRAILLS
     STOP
  END IF


  N_OF_ALL_MEANINGS = 0
  ALL_MEANINGS = ' '
  DO I = 1, TOTAL_BRAILLS
     K = GET_BASE_DECIMAL(BRAILLS(:, :, I))
     DO J = 1, N_OF_LINES_OF_ANSWERS
        IF(ANSWERS(J,I).NE.' ') THEN
           N_OF_ALL_MEANINGS(K) = N_OF_ALL_MEANINGS(K) + 1
           I1 = N_OF_ALL_MEANINGS(K)
           ALL_MEANINGS(I1,K) = ANSWERS(J,I)
        END IF
     END DO
  END DO

  WRITE(*,*) TOTAL_BRAILLS, SUM(N_OF_ALL_MEANINGS)
  WRITE(*,*) TYPE_RANGE_OF_BRAILLS
  WRITE(*,*)
  WRITE(*,*)
  WRITE(*,*)
  WRITE(*,*)


  RETURN
END SUBROUTINE DATA_INITIALIZE




INTEGER FUNCTION GET_BASE_DECIMAL(BBB)
  IMPLICIT  NONE
  INTEGER :: BBB(3,2)
  GET_BASE_DECIMAL = 1 + BBB(1,1) + BBB(2,1)*2 + BBB(3,1)*4 + BBB(1,2)*8 + BBB(2,2)*16 + BBB(3,2)*32
  RETURN
END FUNCTION GET_BASE_DECIMAL



INTEGER FUNCTION GET_A_BRAILL()
  USE DATA
  IMPLICIT  NONE
  REAL :: RAN
  RAND_LOOP:  DO
    CALL RANDOM_NUMBER(RAN)
    GET_A_BRAILL = 0.2 + BRAILL_FROM + BRAILL_RANGE * RAN
    IF(GET_A_BRAILL.LT.BRAILL_FROM) CYCLE RAND_LOOP
    IF(GET_A_BRAILL.GT.BRAILL_TO) CYCLE RAND_LOOP
    EXIT RAND_LOOP
  END DO RAND_LOOP
  RETURN
END FUNCTION GET_A_BRAILL




SUBROUTINE DATA_BASE_CHECK()
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, SQ = 0
  QUESTION_NUMBER = 1
  DO I = 1, N_OF_BRAILL_BASES
      CALL DATA_BASE_CONVERSION(SQ)
      CALL SHOW_IT()
  END DO
  RETURN
END SUBROUTINE DATA_BASE_CHECK




SUBROUTINE DATA_BASE_CONVERSION(SQ)
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J, K, M, N, Q, SQ
  BRAILL_LINES = ' '
  ANSWER_LINES = ' '
  SQ = SQ + 1
  I = 1
  !DO I = 1, N_OF_PRACTICE_BRAILLS_PER_LINE
     Q = GET_A_BRAILL()
     Q = SQ
     BRAILL_QUESTIONS(I) = Q
     J = LENGTH_OF_ANSWERS * I - N_OF_EMPTY_CHARS - 1
     DO N = 1, N_OF_COLUMNS_OF_BRAILLS
        DO M = 1, N_OF_LINES_OF_BRAILLS
           K = BRAILL_BASES(M, N, Q)
           BRAILL_LINES(M)(J:J) = BRAILL_DOTS(K)
        END DO
        J = LENGTH_OF_ANSWERS * I
     END DO

     J = LENGTH_OF_ANSWERS * (I-1) + 1
     K = LENGTH_OF_ANSWERS *  I
     DO M = 1, N_OF_LINES_OF_MEANINGS
        ANSWER_LINES(M)(J:K) = ALL_MEANINGS(M, Q)
     END DO
  !END DO
  RETURN
END SUBROUTINE DATA_BASE_CONVERSION




SUBROUTINE PRACTICE()
  USE ALL_MODULES
  IMPLICIT  NONE
  QUESTION_NUMBER = 1
  PRACTICE_LOOP:  DO
      CALL PRACTICE_TYPE_GENERATION()
      CALL SHOW_IT()
      IF(RRR == 'Q') EXIT PRACTICE_LOOP
  END DO PRACTICE_LOOP
  RETURN
END SUBROUTINE PRACTICE




SUBROUTINE LOAD_A_BRAILL(I)
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J, K, M, N, Q
     Q = GET_A_BRAILL()
     BRAILL_QUESTIONS(I) = Q
     J = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS - N_OF_EMPTY_CHARS - 1
     DO N = 1, N_OF_COLUMNS_OF_BRAILLS
        DO M = 1, N_OF_LINES_OF_BRAILLS
           K = BRAILLS(M, N, Q)
           BRAILL_LINES(M)(J:J) = BRAILL_DOTS(K)
        END DO
        J = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS
     END DO

     J = STARTING_POSITION_IN_LINE + 1
     K = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS
     DO M = 1, N_OF_LINES_OF_ANSWERS
        ANSWER_LINES(M)(J:K) = ANSWERS(M, Q)
     END DO

     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS

  RETURN
END SUBROUTINE LOAD_A_BRAILL




SUBROUTINE LOAD_A_BRAILL_BASE(I)
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J, K, M, N, Q
     Q = GET_A_BRAILL()
     BRAILL_QUESTIONS(I) = Q
     J = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS - N_OF_EMPTY_CHARS - 1
     DO N = 1, N_OF_COLUMNS_OF_BRAILLS
        DO M = 1, N_OF_LINES_OF_BRAILLS
           K = BRAILL_BASES(M, N, Q)
           BRAILL_LINES(M)(J:J) = BRAILL_DOTS(K)
        END DO
        J = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS
     END DO

     J = STARTING_POSITION_IN_LINE + 1
     K = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS
     DO M = 1, N_OF_LINES_OF_MEANINGS
        ANSWER_LINES(M)(J:K) = ALL_MEANINGS(M, Q)
     END DO

     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + LENGTH_OF_ANSWERS

  RETURN
END SUBROUTINE LOAD_A_BRAILL_BASE




SUBROUTINE QUESTION_GENERATION()
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J, K, M, N, Q
  BRAILL_LINES = ' '
  ANSWER_LINES = ' '
  STARTING_POSITION_IN_LINE = 1
  DO I = 1, N_OF_PRACTICE_BRAILLS_PER_LINE
     CALL LOAD_A_BRAILL(I)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1
  END DO
  RETURN
END SUBROUTINE QUESTION_GENERATION




SUBROUTINE QUESTION_GENERATION_SYSYS()
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J, K, M, N, Q
  BRAILL_LINES = ' '
  ANSWER_LINES = ' '
  STARTING_POSITION_IN_LINE = 1
  DO I = 1, 2, 5
     BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_SHENGMU)
     BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_SHENGMU)
     BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
     CALL LOAD_A_BRAILL(I)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1

     BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_YUNMU)
     BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_YUNMU)
     BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
     CALL LOAD_A_BRAILL(I+1)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1

     BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_SHENGMU)
     BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_SHENGMU)
     BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
     CALL LOAD_A_BRAILL(I+2)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1

     BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_YUNMU)
     BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_YUNMU)
     BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
     CALL LOAD_A_BRAILL(I+3)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1

     BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_SHENGDIAO)
     BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_SHENGDIAO)
     BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
     CALL LOAD_A_BRAILL(I+4)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1
  END DO
  RETURN
END SUBROUTINE QUESTION_GENERATION_SYSYS




SUBROUTINE BASE_QUESTION_GENERATION()
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J, K, M, N, Q
  BRAILL_LINES = ' '
  ANSWER_LINES = ' '
  STARTING_POSITION_IN_LINE = 1
  DO I = 1, N_OF_PRACTICE_BRAILLS_PER_LINE
     CALL LOAD_A_BRAILL_BASE(I)
     STARTING_POSITION_IN_LINE = STARTING_POSITION_IN_LINE + 1
  END DO
  RETURN
END SUBROUTINE BASE_QUESTION_GENERATION




SUBROUTINE PRACTICE_TYPE_GENERATION()
  USE ALL_MODULES
  IMPLICIT  NONE
  SELECT CASE (THE_PRACTICE_TYPE)
    CASE (TYPE_OF_NUMBERS)
          BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_NUMBERS)
          BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_NUMBERS)
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL QUESTION_GENERATION()

    CASE (TYPE_OF_E_LETTERS)
          BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_E_LETTERS)
          BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_E_LETTERS)
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL QUESTION_GENERATION()

    !CASE (TYPE_OF_E_PUNCTUATIONS)
    !      BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_E_PUNCTUATIONS)
    !      BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_E_PUNCTUATIONS)
    !      BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
    !      CALL QUESTION_GENERATION()

    CASE (TYPE_OF_C_SHENGMU)
          BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_SHENGMU)
          BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_SHENGMU)
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL QUESTION_GENERATION()

    CASE (TYPE_OF_C_YUNMU)
          BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_YUNMU)
          BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_YUNMU)
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL QUESTION_GENERATION()

    CASE (TYPE_OF_C_SHENGDIAO)
          BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_SHENGDIAO)
          BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_SHENGDIAO)
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL QUESTION_GENERATION()

    !CASE (TYPE_OF_C_PUNCTUATIONS)
    !      BRAILL_FROM  = TYPE_RANGE_OF_BRAILLS(1, TYPE_OF_C_PUNCTUATIONS)
    !      BRAILL_TO    = TYPE_RANGE_OF_BRAILLS(2, TYPE_OF_C_PUNCTUATIONS)
    !      BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
    !      CALL QUESTION_GENERATION()

    CASE (TYPE_OF_ALL_INDIVIDULLY)
          BRAILL_FROM  = 1
          BRAILL_TO    = TOTAL_BRAILLS
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL QUESTION_GENERATION()

    CASE (TYPE_OF_ALL_COMBINED)
          BRAILL_FROM  = 1
          BRAILL_TO    = N_OF_BRAILL_BASES
          BRAILL_RANGE = BRAILL_TO - BRAILL_FROM + 1
          CALL BASE_QUESTION_GENERATION()

    CASE (TYPE_OF_C_SYSYS)
          CALL QUESTION_GENERATION_SYSYS()

    CASE DEFAULT
          WRITE(*,*) "BAD PRACTICE TYPE: ", THE_PRACTICE_TYPE
          STOP
  END SELECT

  RETURN
END SUBROUTINE PRACTICE_TYPE_GENERATION




SUBROUTINE SHOW_IT()
  USE ALL_MODULES
  IMPLICIT  NONE
  INTEGER :: I, J
      WRITE(*,*) STARTING_LINE, QUESTION_NUMBER
      DO I = 1, N_OF_LINES_OF_BRAILLS
         DO J = 1, N_OF_EMPTY_LINES_U
            WRITE(*,*)
         END DO
            WRITE(*,*) TRIM(BRAILL_LINES(I))
         DO J = 1, N_OF_EMPTY_LINES_D
            WRITE(*,*)
         END DO
      END DO
      WRITE(*,*)
      READ(*,*)RRR
      DO I = 1, SIZE(ANSWER_LINES)
         IF(ANSWER_LINES(I).NE.' ')   WRITE(*,*) TRIM(ANSWER_LINES(I))
      END DO
      WRITE(*,*)
      READ(*,*)RRR
      QUESTION_NUMBER = QUESTION_NUMBER + 1
  RETURN
END SUBROUTINE SHOW_IT




SUBROUTINE DATA_FINALIZE()
  USE ALL_MODULES
  IMPLICIT  NONE
  RETURN
END SUBROUTINE DATA_FINALIZE




